# Generated by Django 2.1.7 on 2019-04-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
