# Generated by Django 2.1.7 on 2019-03-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_description',
            field=models.TextField(null=True),
        ),
    ]
