# Generated by Django 2.1.7 on 2019-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='service_type',
            field=models.CharField(default='service', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
