# Generated by Django 2.0.1 on 2019-05-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respondoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.Offer'),
        ),
        migrations.AddField(
            model_name='respondoffer',
            name='request_as_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.Request'),
        ),
    ]
