# Generated by Django 2.0.1 on 2019-04-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
    ]
