# Generated by Django 2.1.7 on 2019-04-13 21:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20190401_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('respond_date', models.DateField(default=datetime.datetime(2019, 4, 13, 21, 39, 58, 373537, tzinfo=utc))),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Request')),
                ('respond_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
