# Generated by Django 2.1.7 on 2019-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/requests', verbose_name='Image url'),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(),
        ),
    ]
