# Generated by Django 2.1.7 on 2019-04-13 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_respondrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondrequest',
            name='respond_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 21, 40, 49, 282794, tzinfo=utc)),
        ),
    ]
