# Generated by Django 2.1.7 on 2019-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20190322_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateField(),
        ),
    ]
