# Generated by Django 2.1.7 on 2019-04-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20190414_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondrequest',
            old_name='respond_user_id',
            new_name='user',
        ),
    ]
