# Generated by Django 2.1.7 on 2019-03-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20190323_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_description',
            field=models.TextField(),
        ),
    ]
