# Generated by Django 2.1.7 on 2019-04-14 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20190414_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='performer',
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
