# Generated by Django 2.1.7 on 2019-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_request_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
